name: Update Playlist

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 12:00 AM IST (06:30 PM UTC) every day
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on push

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Select shuffle method based on day of the week
      id: select_shuffle
      run: |
        day_of_week=$(date +'%u')  # Get the day of the week (1 to 7, Monday to Sunday)
        case $day_of_week in
          1) echo "reverse_shuffle" >> $GITHUB_ENV;;  # Monday
          2) echo "overhand_shuffle" >> $GITHUB_ENV;;  # Tuesday
          3) echo "riffle_shuffle" >> $GITHUB_ENV;;  # Wednesday
          4) echo "pile_shuffle" >> $GITHUB_ENV;;  # Thursday
          5) echo "hindu_shuffle" >> $GITHUB_ENV;;  # Friday
          6) echo "mongean_shuffle" >> $GITHUB_ENV;;  # Saturday
          7) echo "faro_shuffle" >> $GITHUB_ENV;;  # Sunday
        esac

    - name: Shuffle playlist
      run: |
        python3 -c "
import json
import random
import os

def reverse_shuffle(playlist):
    return playlist[::-1]

# Define other shuffle methods here...

# Get the selected shuffle method from the environment variable
shuffle_method = os.getenv('shuffle_method')

with open('playlist.json', 'r') as file:
    playlist = json.load(file)

# Call the selected shuffle method
shuffled_playlist = globals()[shuffle_method](playlist)

with open('playlist.json', 'w') as file:
    json.dump(shuffled_playlist, file, indent=4)
        "

    - name: Commit and push changes
      run: |
        git config --global user.name 'supersez'
        git config --global user.email 'supermanraofficial@gmail.com'
        git add playlist.json
        git commit -m 'Shuffle playlist'
        git push
