name: Shuffle Playlist

on:
  push:
    branches:
      - main

jobs:
  shuffle-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select shuffle method based on day of the week
        id: select_shuffle
        run: |
          day_of_week=$(date +'%u')  # Get the day of the week (1 to 7, Monday to Sunday)
          case $day_of_week in
            1) echo "shuffle_method=reverse_shuffle" >> $GITHUB_ENV;;  # Monday
            2) echo "shuffle_method=overhand_shuffle" >> $GITHUB_ENV;;  # Tuesday
            3) echo "shuffle_method=riffle_shuffle" >> $GITHUB_ENV;;  # Wednesday
            4) echo "shuffle_method=pile_shuffle" >> $GITHUB_ENV;;  # Thursday
            5) echo "shuffle_method=hindu_shuffle" >> $GITHUB_ENV;;  # Friday
            6) echo "shuffle_method=mongean_shuffle" >> $GITHUB_ENV;;  # Saturday
            7) echo "shuffle_method=faro_shuffle" >> $GITHUB_ENV;;  # Sunday
          esac

      - name: Shuffle playlist
        run: |
          # Read the playlist from the file
          playlist=$(<playlist.json)
          
          # Shuffle the playlist based on the selected method
          case $shuffle_method in
            reverse_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'reverse | @json')
              ;;
            overhand_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
            riffle_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
            pile_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
            hindu_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
            mongean_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
            faro_shuffle)
              shuffled_playlist=$(echo "$playlist" | jq -r 'shuffle | @json')
              ;;
          esac
          
          # Write the shuffled playlist back to the file
          echo "$shuffled_playlist" > playlist.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add playlist.json
          git commit -m 'Shuffle playlist'
          git push
